apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    env: dev
spec:
  containers:
  - name: container1
    image: nginx
    resources:
    limits:
      memory: "128Mi"
      cpu: "500m"








