version: '3.1'

services:
  springboot:
    build: .
    image: dockerhandson/product-manager:latest
    container_name: springboot
    ports:
      - 8080:8080
    environment:
    - SPRING_PROFILES_ACTIVE=dev
    - DB_URI=mongodb://mongo:27017
    - DB_NAME=products
    depends_on:
      - mongo
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure   

  mongo:
    image: mongo
    container_name: springboot-mongo
    volumes:
      - data:/data/db
    
volumes:
  data:
  data-bkp:
