# Deployment product-manager
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-manager
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: product-manager
  template:
     metadata:
       name: product-manager
       labels:
         app: product-manager
     spec:
       containers:
       - name: product-manager
         image: dockerhandson/product-manager
         ports:
         - containerPort: 8080
         env:
         - name: SPRING_PROFILES_ACTIVE
           value: dev
         - name: DB_URI
           value: mongodb://mongo:27017
         - name: DB_NAME
           value: products       
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: product-manager
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: product-manager
---
# Mongo host path rc
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        hostPath:
         path: /tmp/dbbackup
---
# Mongo Node Port RC
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
